import { Geist, Geist_Mono } from "next/font/google";
import "@/style/globals.css";
import { LeftSideBar, RightSideBar } from "@/components/layouts/side-bar";
import MobileNav from "@/components/layouts/mobile-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-dark-DEFAULT text-gray-100 font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
